from django.urls import path
from .import views

urlpatterns = [
    path('',views.index,name='index'),
    path('plots/',views.plots,name='plots'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('contact_us/',views.contact_us,name='contact_us'),
    path('postproperty/',views.postproperty,name='postproperty'),
    path('buy/',views.buy,name='buy'),
    path('rent/',views.rent,name='rent'),
    path('pg_coliving/',views.pg_coliving,name='pg_coliving'),
    path('view_details/<int:property_id>',views.view_details,name='view_details'),
    path('view_posted_property/',views.view_posted_property,name='view_posted_property'),
    path('view/',views.view,name='view'),
    path('enquiry/<int:property_id>',views.enquiry,name='enquiry'),
    path('enquired_property/',views.enquired_property,name='enquired_property'),
    path('update_property/<int:property_id>',views.update_property,name='update_property'),
    path('delete_property/<int:property_id>',views.delete_property,name='delete_property'),
    path('search/',views.search,name='search'),
    path('AgriculturalLand/',views.AgriculturalLand,name='AgriculturalLand'),
    path('CommercialSpace/',views.CommercialSpace,name='CommercialSpace'),
    path('logout/',views.logout,name='logout'),
    path('agent_register/',views.agent_register,name='agent_register'),
    path('agent_login/',views.agent_login,name='agent_login'),
    path('agentdashboard/',views.agentdashboard,name='agentdashboard'),
    path('fill_profile/',views.fill_profile,name='fill_profile'),
    path('viewprofile/',views.viewprofile,name='viewprofile'),
    path('view_all_property/',views.view_all_property,name='view_all_property'),
    path('editProfile/',views.editProfile,name='editProfile'),
    path('details/<int:property_id>',views.details,name='details'),
    path('beginner_guide/',views.beginner_guide,name='beginner_guide'),
    path('flats/',views.flats,name='flats'),
    path('view_agent_details/<int:agent_id>',views.view_agent_details,name='view_agent_details'),
    path('properties/',views.properties,name='properties'),
    path('view_agents/',views.view_agents,name='view_agents'),
]