# Generated by Django 5.0.3 on 2024-04-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('member_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30)),
                ('contactno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
