# Generated by Django 5.0.3 on 2024-04-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='contactno',
        ),
    ]
