# Generated by Django 5.0.3 on 2024-04-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_remove_login_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='contactno',
        ),
    ]
