# Generated by Django 5.0.3 on 2024-04-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_remove_members_contactno'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('property_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=50)),
                ('property_price', models.IntegerField(max_length=50)),
                ('property_location', models.CharField(max_length=50)),
                ('property_image', models.FileField(upload_to='Property_Images/')),
                ('property_area', models.IntegerField()),
                ('property_description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_contact', models.IntegerField()),
                ('owner_email', models.EmailField(max_length=30)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeApp.members')),
            ],
        ),
    ]
