# Generated by Django 5.0.3 on 2024-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.FileField(upload_to='media/Property_Images/'),
        ),
    ]
