# Generated by Django 5.0.3 on 2024-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0006_alter_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.FileField(upload_to='Property_Images/'),
        ),
    ]
