# Generated by Django 5.0.3 on 2024-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0008_alter_property_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(default=None, null=True, upload_to='Property_Images/'),
        ),
    ]
