# Generated by Django 5.0.3 on 2024-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0011_alter_property_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
