# Generated by Django 5.0.3 on 2024-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0012_rename_property_area_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='action',
            field=models.CharField(default='sell', max_length=30),
        ),
    ]
