# Generated by Django 5.0.3 on 2024-04-21 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0013_property_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
    ]
