# Generated by Django 5.0.3 on 2024-04-22 15:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0014_alter_property_created_alter_property_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_id', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_contact', models.IntegerField(max_length=10)),
                ('posted_on', models.DateField(default=datetime.date(2024, 4, 22))),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeApp.property')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeApp.members')),
            ],
        ),
    ]
