# Generated by Django 5.0.3 on 2024-04-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0016_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sender_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Not Furnished', 'Not Furnished'), ('Semi Furnished', 'Semi Furnished'), ('N/A', 'N/A')], max_length=128),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
