# Generated by Django 5.0.3 on 2024-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0018_property_city_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
