# Generated by Django 5.0.3 on 2024-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0022_alter_property_city_alter_property_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Furnished', 'Furnished'), ('Not Furnished', 'Not Furnished'), ('Semi Furnished', 'Semi Furnished')], max_length=128),
        ),
    ]
