# Generated by Django 5.0.3 on 2024-05-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0025_alter_property_bathrooms_alter_property_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_register',
            fields=[
                ('agent_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('agent_email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='user_type',
            field=models.CharField(choices=[('Buyer/Owner', 'Buyer/Owner'), ('Agent', 'Agent')], default='Buyer/Owner', max_length=20),
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=30)),
                ('agent_contact', models.IntegerField()),
                ('agent_email', models.EmailField(max_length=40)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('operating_city', models.CharField(max_length=50)),
                ('operating_locations', models.CharField(max_length=50)),
                ('deals_in', models.CharField(max_length=60)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeApp.agent_register')),
            ],
        ),
    ]
