# Generated by Django 5.0.3 on 2024-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0026_agent_register_members_user_type_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user_type',
        ),
    ]
