# Generated by Django 5.0.3 on 2024-05-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0027_remove_members_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='agent_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='agent_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='agent_contact',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='deals_in',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='operating_city',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='operating_locations',
        ),
        migrations.AddField(
            model_name='agents',
            name='password',
            field=models.CharField(default=123, max_length=20),
        ),
        migrations.CreateModel(
            name='AgentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=30)),
                ('agent_contact', models.IntegerField()),
                ('agent_email', models.EmailField(max_length=40)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('operating_city', models.CharField(max_length=50)),
                ('operating_locations', models.CharField(max_length=50)),
                ('deals_in', models.CharField(max_length=60)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeApp.agents')),
            ],
        ),
        migrations.DeleteModel(
            name='agent_register',
        ),
    ]
