# Generated by Django 5.0.3 on 2024-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0028_alter_agents_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsinfo',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='agent_images/'),
        ),
    ]
