# Generated by Django 5.0.3 on 2024-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0029_agentsinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsinfo',
            name='image',
            field=models.FileField(upload_to='agent_images/'),
        ),
    ]
