# Generated by Django 5.0.3 on 2024-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0030_alter_agentsinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsinfo',
            name='operating_since',
            field=models.IntegerField(default=2015),
        ),
    ]
